### PR TITLE
Added actor framework - currently two -main functions (additional one…

### PR DESCRIPTION
**Pull request by TonyLo1**
… in nars.core)

### CODE REVIEW

**Comment by TonyLo1** [comment]
All rasom's comments have been actioned

**Comment by 0xc1c4da** [comment]
code looks good to me, nice work @TonyLo1 

I think we should have a discussion about package structure and eliminate the existing main, ideally we use @TonyLo1 's main and boot into the actor system.

What do you guys think about moving codeblock in main to an aptly-named function, so we can call it explicitly from REPL to boot up actor system? (-main) feels abit weird to me?

sidenote: @rasom we should remove the core.logic and do abit of cleanup.

**Comment by TonyLo1** [comment]
My intention is to add a gen-server (actor) as the top level entry point - this gives clean shutdown capability - I have no problem with (-main) being changed

**Comment by TonyLo1** [comment]
This is a template for the gen-server:

```
(defprotocol Server
  (init [_])
  (handle-call [_])
  (handle-cast [_])
  (handle-info [_])
  (handle-timeout [_])
  (terminate [_])
  )

(let [gs {spawn
          (gen-server (reify Server 
                        (init [_])
                        (terminate [_ cause])
                        (handle-cast [_])))}]

  (cast! gs :initialise-system-msg))
```

**Pull request closed without merging**
